// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK2gV6bTx1kJ4VvMidbHsSNopCpBWFdLI',
    appId: '1:812316452629:web:4b9e33bfbea8cd176feb1c',
    messagingSenderId: '812316452629',
    projectId: 'instagramtutorial-60d3e',
    authDomain: 'instagramtutorial-60d3e.firebaseapp.com',
    storageBucket: 'instagramtutorial-60d3e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ6ISYKAzL0pzXsAjfgzcRAu124xj5J60',
    appId: '1:812316452629:android:9f1c03a7377f5f586feb1c',
    messagingSenderId: '812316452629',
    projectId: 'instagramtutorial-60d3e',
    storageBucket: 'instagramtutorial-60d3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANqkpog9k4AdhoWX6LCEpUBZFwbzN9rHE',
    appId: '1:812316452629:ios:4ae629ba4d16150d6feb1c',
    messagingSenderId: '812316452629',
    projectId: 'instagramtutorial-60d3e',
    storageBucket: 'instagramtutorial-60d3e.appspot.com',
    iosBundleId: 'com.example.instagramTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANqkpog9k4AdhoWX6LCEpUBZFwbzN9rHE',
    appId: '1:812316452629:ios:17e505e156b118456feb1c',
    messagingSenderId: '812316452629',
    projectId: 'instagramtutorial-60d3e',
    storageBucket: 'instagramtutorial-60d3e.appspot.com',
    iosBundleId: 'com.example.instagramTutorial.RunnerTests',
  );
}
